version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
