// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/himura467/slack-review-request-bot/internal/config"
	"github.com/himura467/slack-review-request-bot/internal/domain/model"
	"github.com/himura467/slack-review-request-bot/internal/infrastructure"
	"github.com/himura467/slack-review-request-bot/internal/usecase"
)

// Injectors from wire.go:

func initializeApp() *app {
	slackConfig := config.NewSlackConfig()
	oAuthToken := provideOAuthToken(slackConfig)
	signingSecret := provideSigningSecret(slackConfig)
	client := infrastructure.NewClient(oAuthToken, signingSecret)
	slackUsecaseImpl := usecase.NewSlackUsecase(client)
	mainApp := newApp(slackUsecaseImpl)
	return mainApp
}

// wire.go:

func provideOAuthToken(cfg *config.SlackConfig) model.OAuthToken {
	return cfg.OAuthToken
}

func provideSigningSecret(cfg *config.SlackConfig) model.SigningSecret {
	return cfg.SigningSecret
}
